HOSTNAME: "TEST-HOST"
HOURS_API:
  enabled: false
# Test needs to be under http otherwise jquery cannot be loaded
PURL_EMBED_PROVIDER: 'http://embed.stanford.edu/embed'
SU_AFFILIATIONS:
  - test-stanford:test
EXHIBITS_ACCESS_PANEL:
  enabled: true
LIB_GUIDES:
  MINI_BENTO_ENABLED: true
