HOSTNAME: "TEST-HOST"
# Test needs to be under http otherwise jquery cannot be loaded
PURL_EMBED_PROVIDER: 'http://embed.stanford.edu/embed'
SU_AFFILIATIONS:
  - test-stanford:test
SHOW_IIIF_PANEL: true
